export { Routes } from "./Routes.ts";
export {
  ABOUT_INFO_LINKS,
  CONTACTS_INFO_LINKS,
  PRODUCT_CATEGORIES_WITH_BRANDS,
  PRODUCT_CATEGORIES,
  BREADCRUMBS,
  GET_IN_TOUCH_LINKS,
  CONNECTIONS_LINKS,
  FOOTER_NAVIGATION_TITLES,
  EARNINGS_LINKS,
  ACCOUNT_LINKS,
  NAVIGATION_KEYS,
} from "./StaticNavigation";
