export { createContextDefaultState } from "./createContextDefaultState.ts";
export { removeDataAttribute, setDataAttribute } from "./manageDataAttributes.ts";
export { getProductsCategoriesWithBrands } from "./getProductsCategoriesWithBrands.ts";
export { getProductsCategories } from "./getProductsCategories.ts";
export { getSlugString } from "./getSlugString.ts";
export { generateCharacteristics } from "./generateCharacteristics.ts";
export { checkCategory } from "./checkCategory.ts";
export { applyTrimAndLowerCase } from "./applyTrimAndLowerCase.ts";
export { getTitleBrand } from "./getTitleBrand.ts";
export * from "./getMinMaxProductPrice.ts";
export * from "./checkPriceCorrectValue.ts";
