export { createContextDefaultState } from "./createContextDefaultState.ts";
export { removeDataAttribute, setDataAttribute } from "./manageDataAttributes.ts";
export { getProductsCategoriesWithBrands } from "./getProductsCategoriesWithBrands.ts";
export { getProductsCategories } from "./getProductsCategories.ts";
export { getSlugString } from "./getSlugString.ts";
export { checkCategory } from "./checkCategory.ts";
export { applyTrimAndLowerCase } from "./applyTrimAndLowerCase.ts";
export { getTitleBrand } from "./getTitleBrand.ts";
export { getCountPages } from "./getCountPages.ts";
export { sortFunctions } from "./sortFunctions.ts";
export { getAnimationVariant } from "./getAnimationVariant.ts";
export { getProductDiscount } from "./getProductDiscount.ts";
export { getProductCharacteristics } from "./getProductCharacteristics.ts";
export { getProductId } from "./getProductId.ts";
export { getDeliveryTime } from "./getDeliveryTime.ts";
export { getProductRating } from "./getProductRating.ts";
export * from "./generateCharacteristics.ts";
export * from "./getMinMaxProductPrice.ts";
export * from "./checkPriceCorrectValue.ts";
